### ISSUE TITLE
revisionstrike_post_types filter not being called

### ISSUE THREAD

**Issue by petenelson** [stevegrunwell/revision-strike#23]
From our discussion on Slack, working on a fix for the `revisionstrike_post_types` not being called.  This is occurring because the code is checking for a null value in `$args['post_type']` but that value is never null due to the defaults in the plugin.

After applying the fix locally and testing the filter, I found the syntax for the SQL statement is incorrect (see below), so the PR will include a fix and test for that as well.

`SELECT r.ID FROM wp_posts r
LEFT JOIN wp_posts p ON r.post_parent = p.ID
WHERE r.post_type = 'revision' AND p.post_type IN ('post\', \'page') AND p.post_date < '2016-05-23'
ORDER BY p.post_date ASC
LIMIT 50`

**Comment by stevegrunwell** [comment]
Fixed by #24.

Thanks for the PR, @petenelson!

**Comment by petenelson** [comment]
![At last...](https://petenelson.com/wp-content/uploads/2011/08/at-last.gif)
